### ISSUE TITLE
[BUG] Named BBcode style links do not allow spaces in link names

### ISSUE THREAD

**Issue by Undisguised-Art** [danbooru/dtext_rb#6]
Issue
---
Named BBcode style links do not allow spaces in link names.

Example
---
DText:
```
[url=https://github.com]Github_Site[/url]
[url=https://github.com]Github Site[/url]
```
Result:
>[Github_Site](https://github.com)
>[url=[https://github.com](https://github.com)]Github Site[/url]

Cause
---
The issue is caused by stripping spaces/tabs before the closing tag [[dtext.cpp.rl L199](https://github.com/danbooru/dtext_rb/blob/c7b9461479f8f0369d0603cfa34eaafccbaee85f/ext/dtext/dtext.cpp.rl#L199)]:
```ragel
named_bbcode_link   = '[url'i ws* '=' ws* (bbcode_url :>> ws* ']') ws* (nonnewline+ >mark_a1 %mark_a2 :>> ws* '[/url]'i);
```

**Comment by Undisguised-Art** [comment]
Potential Fix:
---

Leave `ws` in the captured link title, then remove it later when the title is parsed with the basic_inline parser.
This would ensure that all named link titles handle `ws` in the same way, and this would simplify the matching rules for link types.

Change on [L199](https://github.com/danbooru/dtext_rb/blob/c7b9461479f8f0369d0603cfa34eaafccbaee85f/ext/dtext/dtext.cpp.rl#L199):
```diff
-named_bbcode_link   = '[url'i ws* '=' ws* (bbcode_url :>> ws* ']') ws* (nonnewline+ >mark_a1 %mark_a2 :>> ws* '[/url]'i);
+named_bbcode_link   = '[url'i ws* '=' ws* (bbcode_url :>> ws* ']') (nonnewline+ >mark_a1 %mark_a2 :>> '[/url]'i);
```
Change in `basic_inline` [L285-L296](https://github.com/danbooru/dtext_rb/blob/c7b9461479f8f0369d0603cfa34eaafccbaee85f/ext/dtext/dtext.cpp.rl#L285-L296):
```diff
basic_inline := |*
   close_s => { dstack_close_element(sm, INLINE_S); };
   open_u  => { dstack_open_element(sm,  INLINE_U, "<u>"); };
   close_u => { dstack_close_element(sm, INLINE_U); };
-  eos;
+  ws* eos ws*; # Remove leading and trailing `ws`.
+  ws+ => { append_html_escaped(sm, ' '); }; # Convert tabs to spaces and remove repeated `ws`.
   any => { append_html_escaped(sm, fc); };
 *|;
```

**Comment by evazion** [comment]
> Leave `ws` in the captured link title, then remove it later when the title is parsed with the basic_inline parser. This would ensure that all named link titles handle `ws` in the same way, and this would simplify the matching rules for link types.

The problem with stripping leading/trailing spaces is that it would break cases like this:

```
foo" bar":http://google.com
```

where someone accidentally put the space inside the link instead of before the link, and they didn't notice because there was still a space between the words. This situation is rare but it does happen. There are about 500 instances of named links with a leading space on Danbooru. The space doesn't matter in all of them, but it does in some.

This number might be low enough that we decide it's worth stripping the spaces anyway, but I'd prefer to do that in a separate commit.

Stripping spaces would also make it possible to generate empty links by doing `" ":http://google.com`, unless we said that links can't contain only whitespace, which would break links that do this on purpose (a few do exist).

Probably the best thing to do would be to make it so that any leading/trailing spaces inside the link are placed outside the link, but that would be a bit more complicated.
